config/routes.rb
Rails.application.routes.draw do

  concern :comments do
    resources :comments, only: [:create]
  end
  resources :tags, only: [:index, :show]

  resources :users, only: [:new, :create, :show], concerns: :comments
  resources :projects, concerns: :comments

  resources :sessions, only: [:index, :create, :destroy, :new]

  resources :pledges, only: [:create]

  resources :categories

  root 'projects#index'

  get 'login' => 'sessions#new', as: 'login'
  get 'logout' => 'sessions#destroy', as: 'logout'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :projects
  validates_uniqueness_of :name
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
  belongs_to :user
  validates_presence_of :text
end

app/models/pledge.rb
class Pledge < ActiveRecord::Base
  belongs_to :user
  belongs_to :reward
  has_one :project, through: :reward
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :rewards

  # added below line so rewards will show up in edit page. without this line the nested form in the projects/edit.html.erb  for the rewards will be blank.
  accepts_nested_attributes_for :rewards, :reject_if => :all_blank, :allow_destroy => true
  belongs_to :category
  belongs_to :owner, class_name: 'User', inverse_of: :owned_projects
  has_many :pledges, through: :rewards
  has_many :comments, as: :commentable

  acts_as_taggable

end

app/models/reward.rb
class Reward < ActiveRecord::Base
  belongs_to :project
  has_many :pledges
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  has_many :owned_projects, class_name: 'Project', foreign_key: 'owner_id', inverse_of: :owner
  has_many :pledges
  has_many :projects, through: :pledges
  has_many :comments, as: :commentable

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email, :first_name, :last_name
  validates_uniqueness_of :email

  def name
    [first_name, last_name].join(' ')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.


  def not_authenticated
    redirect_to login_path, :alert => "Please login to access this page!"
  end
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index

    @categories = Category.order(:name).page(params[:page])

    respond_to :html, :js
  end

  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create

    if params[:project_id]
      commentable = Project.find(params[:project_id])
    elsif params[:user_id]
      commentable = User.find(params[:user_id])
    else
      raise 'Invalid Commentable'
    end
    @comment = commentable.comments.build(comment_params)
    @comment.user = current_user
    @comment.save

    respond_to do |format|
      format.js
      format.html {redirect_to(polymorphic_path(commentable))}
    end
  end

  def comment_params
    params.permit(:text)
  end
end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController

	def create
		# putting @project so @project will be binded to the create method
		# now you can use @project in the projects/_individual_project.html.erb
		@project = Project.find(params[:project_id])
		@pledge = Pledge.new(reward: Reward.find(params[:reward_id]))

		# ensure that the pledge user is the current user
		@pledge.user = current_user
		# find the reward based on current :reward_id
		@pledge.amount = Reward.find(params[:reward_id]).amount
		#assigning the pledge to the project
		@pledge.project = @project

		@pledge.save

		respond_to do |format|
		 	format.js  #allows controller to respond in javascript
		 	format.html { redirect_to project_url(params[:project_id]) } #allows controller to respond to html and sends it back to the correct project
		end

		if @project.pledges.sum(:amount) >= @project.funding_goal 
	 		# binding.pry
	 		@project.pledges.map{|x| x.user }.each do |backer|
	 			UserMailer.goal_met_email(backer, @project).deliver
	 			puts "MAIL SENT"
	 		end
	 	end
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :require_login, except: :index

	# calls the user_ownership method for the :edit and :update commands to check to see if the user actually owns the project before they can see the edit page.
	before_action :user_ownership, only: [:edit, :update]

	def index
		@projects = Project.order('projects.created_at DESC').page(params[:page])

		respond_to do |format|
			format.js
			format.html
		end
	end

	def show
		@project = Project.find(params[:id])
		@rewards = @project.rewards
		@comment = Comment.new

	end

	def edit
		@project = Project.find(params[:id])
	end

	def update
		@project = Project.find(params[:id])

		if @project.update_attributes(project_params)
			redirect_to project_path(@project), notice: 'Successfully Selected Reward'
		else
			render :edit
		end
	end

	def new
		# you must be required to logged in to create a new projects.  You will be directed into the login page.
		require_login
		@project = Project.new
		@project.rewards.build
	end

	def create
		@project = Project.new(project_params)
		@project.owner = current_user # When you create new project, you will insert in the current_user ID as the @project.owner

		if @project.save
			redirect_to projects_path
		else
			render :new
		end
	end

	private
	def project_params
		params.require(:project).permit(:name, :description, :start_date, :end_date, :funding_goal, :category_id, :tag_list, rewards_attributes: [:title, :description, :amount, :id, :_destroy])
	end

	# this private method checks to see if the current user owns a project
	def user_ownership
		@project = Project.find(params[:id])
		redirect_to project_path(@project) unless current_user == @project.owner
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = login(params[:email], params[:password], params[:remember_me])
    if user
      redirect_back_or_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Email or password was invalid"
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    if params[:id] =~ /\d+/
      @projects = Project.tagged_with(ActsAsTaggableOn::Tag.find(params[:id]))
    else
      @projects = Project.tagged_with(params[:id])
    end
  end

  def index
    @tags = Project.tag_counts.order(taggings_count: :desc).page(params[:page])
    respond_to :js, :html
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # automatically log in the user to the website after he's created himself - this is method gained from sorcery
      auto_login(@user)
      # used when a user tries to access a page while logged out, is asked to login
      redirect_back_or_to root_url, :notice => "Signed up!"
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @comment = Comment.new
  end

  private
  def user_params
    params.require(:user).permit(:email, :first_name, :last_name,:password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pledges_helper.rb
module PledgesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category.html.erb
<li class="category">
  <h3><%= category.name %></h3>
  <p>
    <%= link_to 'Show Projects', category_path(category) %>
    <%= link_to 'Edit', edit_category_path(category) %>
    <%= link_to 'Delete', category_path(category), method: 'delete' %>
  </p>
</li>

app/views/categories/index.html.erb
<div class="row">
  <div class="large-12 columns">

		<%= paginate @categories %>
		<ul id="categories">
		<%= render @categories %>
		</ul>
		<%= paginate @categories %>

	</div>
</div>

app/views/categories/index.js.erb
$('.pagination').html("<%= j(paginate @categories) %>");
$('#categories').append("<%= j(render @categories) %>");

app/views/categories/show.html.erb
<div class="row">
  <div class="large-12 columns">
		<h2><%= @category.name %></h2>
		<ul>
		<% @category.projects.each do |project| %>
		    <li><%= link_to project.name, project_path(project) %></li>
		<% end %>
		</ul>
	</div>
</div>

app/views/comments/_comment.html.erb
<div class="comment">
  <p><%= comment.text %></p>
  <p>Written by <%= comment.user.name %> on <%= comment.created_at %></p>
</div>

app/views/comments/_comment_errors.html.erb
<% @comment.errors.each do |attribute, error| %>
    <li><%= attribute %> <%= error %></li>
<% end %>

app/views/comments/create.js.erb
<% if @comment.errors.empty? %>
$('#comments').append("<%= j(render @comment ) %>");
$('#comment_form_errors').empty();
$('#text').val('');
<% else %>
$('#comment_form_errors').html("<%= j(render partial: 'comments/comment_errors') %>");
<% end %>

app/views/pledges/create.html.erb
<h1>Pledge created</h1>

<p><%= params %></p>

app/views/pledges/create.js.erb
// j is shorthand for escape_javascript
// The following code will get the partial from projects/_individual_projects.html.erb
// and force it to be rendered under HTML in the <div id="individual_project">

$("#individual_project").html('<%= j render :partial => 'projects/individual_project' %>');
//alert("I'm coming from rails; create.js.erb in pledges");

app/views/projects/_individual_project.html.erb
<% puts "Got here!" %>

<h1><%= @project.name %></h1>

<% if @project.pledges.where(user: current_user).size > 0 %>
  <h2>You Have Backed This Project for <%= number_to_currency(@project.pledges.where(user: current_user).sum('pledges.amount'), precision: 0) %></h2>
<% end %>
<ul>
  <li>Description: <%= @project.description %></li>
  <li>Start Date: <%= @project.start_date %></li>
  <li>End Date: <%= @project.end_date %></li>
  <li>Funding Goal: $<%= @project.funding_goal %></li>
  <li>Total Pledges: <%= number_to_currency(@project.pledges.sum(:amount), precision: 0) %></li>
  <li>Category: <%= @project.category.name %></li>
  <li>Tags: <% @project.tags.each do |tag| %>
            <%= link_to tag.name, tag_path(tag) %>
        <% end %>
  </li>
  <li>Created By:
    <% if @project.owner %>
        <%= link_to @project.owner.name, user_path(@project.owner) %>
    <% else %>
        N/A (no user specified)
    <% end %>
  </li>
    <% if current_user == @project.owner %>
      <li> Days to Completion: <%= distance_of_time_in_words_to_now(@project.end_date) %>(
        <%= (@project.end_date.to_date - Date.current).to_i %> days)
      </li>
      <li><%= link_to "Edit Project", edit_project_path(@project) %></li>
    <% end %>
</ul>

app/views/projects/_project.html.erb
    <div class="large-3 small-6 columns project-item">
      <%= link_to project_path(project.id) do %>
          <img src="http://placehold.it/250x250&text=Project"/>
          <div class="panel">
            <h6><%= project.name %></h6>
            <p>
              <%= project.description %>

            <p>
              Pledged:
              <%= number_to_currency(project.pledges.sum(:amount), precision: 0) %>
              /
              <%= number_to_currency(project.funding_goal) %>
            </p>
            <p>
              Days to Completion:
              <%= distance_of_time_in_words_to_now(project.end_date) %>
              (<%= (project.end_date.to_date - Date.current).to_i %> days)
            </p>

            </p>
          </div>
      <% end %>
    </div>

app/views/projects/_project_form.html.erb
<%= form_for(@project) do |f| %>
    <p>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :description %>
      <%= f.text_area :description %>
    </p>
    <p>
      <%= f.label :start_date %>
      <%= f.date_select :start_date %>
    </p>
    <p>
      <%= f.label :end_date %>
      <%= f.date_select :end_date %>
    </p>
    <p>
      <%= f.label :tags %>
      <%= f.text_field :tag_list %>
    </p>
    <p>
      <%= f.label :funding_goal %>
      <%= f.text_field :funding_goal %>
    </p>
    <h3>Category</h3>
    <%= f.collection_select(:category_id, Category.all, 'id', 'name') %>

    <h4>Rewards</h4>

    <div id="rewards_container">
      <%= f.fields_for :rewards do |rwd| %>
          <%= render "reward_fields", f: rwd %>
      <% end %>
      <%= link_to_add_association "Add Reward", f, :rewards %>
    </div>

    <p>
      <%= f.submit "Submit", class: "button" %>
    </p>
<% end %>

app/views/projects/_reward_fields.html.erb
<div class="reward">
    <p>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </p>
    <p>
      <%= f.label :description %>
      <%= f.text_area :description %>
    </p>
    <p>
      <%= f.label :amount %>
      <%= f.text_field :amount %>
    </p>


  <!-- wrapper_class: method is a cocoon special method! -->
    <%= link_to_remove_association "Remove Reward", f, wrapper_class: 'reward' %>
</div>

app/views/projects/edit.html.erb
<%= link_to "Back", projects_path %>

<h1>Editing Project</h1>

<%= render 'project_form' %>

app/views/projects/index.html.erb
<% if current_user && current_user.pledges.size > 0 %>
    <h3>Total Pledges <%= number_to_currency(current_user.pledges.sum(:amount), precision: 0) %></h3>
    <ul>
      <% current_user.projects.distinct.each do |project| %>
          <li><%= link_to project.name, "/projects/#{project.id}" %> -
            <% if project.pledges.where(user: current_user).size > 0 %>
                You've Pledged: <%= number_to_currency(project.pledges.where(user: current_user).sum('pledges.amount'), precision: 0)
          %>
            <% end %></li>
      <% end %>
    </ul>
<% end %>

 
  <div class="row">
    <div class="large-12 columns">

      <h2>All Projects</h2>
      <h3><small><%= page_entries_info @projects %></small></h3>

      <div class="row">

        <%= paginate @projects %>
        <ul id="projects">

        <%= render @projects  %>

        </ul>
      </div>
    </div>
  </div>
 
 
 
  <div class="row">
    <div class="large-12 columns">
      <div class="row">

        <%= paginate @projects %>
 
        <div class="large-8 columns">
          <div class="panel radius">
 
          <div class="row">
          <div class="large-6 small-6 columns">

            <h4>Header</h4><hr/>
            <h5 class="subheader">Risus ligula, aliquam nec fermentum vitae, sollicitudin eget urna. Donec dignissim nibh fermentum odio ornare sagittis.
            </h5>
 
          <div class="show-for-small" align="center">
            <a href="#" class="small radius button">Call To Action!</a><br>
 
            <a href="#" class="small radius button">Call To Action!</a>
          </div>
 
          </div>
          <div class="large-6 small-6 columns">
 
            <p>Suspendisse ultrices ornare tempor. Aenean eget ultricies libero. Phasellus non ipsum eros. Vivamus at dignissim massa. Aenean dolor libero, blandit quis interdum et, malesuada nec ligula. Nullam erat erat, eleifend sed pulvinar ac. Suspendisse ultrices ornare tempor. Aenean eget ultricies libero.
          </p>
        </div>
 
        </div>
        </div>
        </div>
 
          <div class="large-4 columns hide-for-small">
 
          <h4>Get In Touch!</h4><hr/>
 
          <a class="large button expand" href="#">
            Call To Action!
          </a>
 
          <a class="large button expand" href="#">
            Call To Action!
          </a>
 
 
        </div>
 
     
 
      </div>
    </div>
  </div>

app/views/projects/index.js.erb
// looks at the <ul id="projects"> in the views/projects/index.html.erb file to append the newly rendered projects.
$('#projects').append('<%= j render(@projects) %>');

app/views/projects/new.html.erb
<div class="row">
	<div class="large-12 columns">
		<h1>New Project</h1>
		<%= render 'project_form' %>
	</div>
</div>

app/views/projects/show.html.erb
<div class="row">
  <div class="large-12 columns">
    <div id="individual_project">
      <%= render :partial => "/projects/individual_project" %>
    </div>
  </div>
</div>

<div class="row">
  <div class="large-12 columns">
    <h2>Rewards</h2>

    <% @rewards.each do |reward| %>
        <ul>
          <li>Title: <%= reward.title %></li>
          <li>Description: <%= reward.description %></li>
          <li>Amount: $<%= reward.amount %></li>
          <!-- After link is selected, for response sent by AJAX instead of by html add , remote: true -->
          <% if current_user != @project.owner %>
            <!-- ensure that the reward_id: that is being passed into the pledges_path is the current reward (reward.id) -->
            <%= form_tag pledges_path(reward_id: reward.id, project_id: @project), method: :post, class: 'reward-button' do %>
                <%= submit_tag "Select this reward", class: 'button' %>
            <% end %>
          <% else %>
            <li>Number of Unique Backers: <%= reward.pledges.select(:user_id).count %>!!!</li>
          <% end %>
        </ul>
    <% end %>
  </div>
  <!-- project owner shouldn't be able to make comments on his own project -->
  <% if current_user != @project.owner %>
    <%= render partial: 'shared/comments_section', locals: {comments: @project.comments, commentable: @project} %>
  <% end %>
</div>

app/views/projects/show.js.erb
// $("#individual_project").html("<%= j(render(:partial => '/projects/individual_project')) %>");
alert("I'm coming from rails")

app/views/tags/_tag.html.erb
<li><%= link_to tag.name, tag_path(tag) %> <%= tag.taggings_count %></li>

app/views/tags/index.html.erb
<ul id="tags">
  <%= render partial: 'tags/tag', collection: @tags %>
</ul>
<%= paginate @tags %>

app/views/tags/index.js.erb
$('.pagination').html("<%= j(paginate @tags) %>");
$('#tags').append("<%= j(render partial: 'tags/tag', collection: @tags) %>");

app/views/tags/show.html.erb
<ul id="tags"><% @projects.each do |project|  %>
      <li><%= link_to project.name, project_path(project) %></li>
<% end %></ul>

app/views/users/new.html.erb
<div class="row">
  <div class="large-12 columns">
    <h1>Sign up for Crowd Funder!</h1>

    <%= form_for @user do |f| %>
        <% if @user.errors.any? %>
            <div class="error_messages">
              <h2>Form is invalid</h2>
              <ul>
                <% for message in @user.errors.full_messages %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <div class="field">
          <%= f.label :email %>
          <%= f.text_field :email %>
        </div>
        <div class="field">
          <%= f.label :first_name %>
          <%= f.text_field :first_name %>
        </div>
        <div class="field">
          <%= f.label :last_name %>
          <%= f.text_field :last_name %>
        </div>
        <div class="field">
          <%= f.label :password %>
          <%= f.password_field :password %>
        </div>
        <div class="field">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation %>
        </div>
        <div class="actions"><%= f.submit %></div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="large-12 columns">
    <h2><%= @user.name %></h2>
    <%= render partial: 'shared/comments_section', locals: {comments: @user.comments, commentable: @user} %>
  </div>
</div>