config/routes.rb
Rails.application.routes.draw do

  concern :comments do
    resources :comments, only: [:create]
  end
  resources :tags, only: [:index, :show]

  resources :users, only: [:new, :create, :show], concerns: :comments
  resources :projects, concerns: :comments

  resources :sessions, only: [:index, :create, :destroy, :new]

  resources :pledges, only: [:create]

  resources :categories

  root 'projects#index'

  get 'login' => 'sessions#new', as: 'login'
  get 'logout' => 'sessions#destroy', as: 'logout'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :projects
  validates_uniqueness_of :name
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
  belongs_to :user
  validates_presence_of :text
end

app/models/pledge.rb
class Pledge < ActiveRecord::Base
  belongs_to :user
  belongs_to :reward
  has_one :project, through: :reward
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :rewards

  # added below line so rewards will show up in edit page. without this line the nested form in the projects/edit.html.erb  for the rewards will be blank.
  accepts_nested_attributes_for :rewards, :reject_if => :all_blank, :allow_destroy => true
  belongs_to :category
  belongs_to :owner, class_name: 'User', inverse_of: :owned_projects
  has_many :pledges, through: :rewards
  has_many :comments, as: :commentable

  acts_as_taggable

end

app/models/reward.rb
class Reward < ActiveRecord::Base
  belongs_to :project
  has_many :pledges
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  has_many :owned_projects, class_name: 'Project', foreign_key: 'owner_id', inverse_of: :owner
  has_many :pledges
  has_many :projects, through: :pledges
  has_many :comments, as: :commentable

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email, :first_name, :last_name
  validates_uniqueness_of :email

  def name
    [first_name, last_name].join(' ')
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create

    if params[:project_id]
      commentable = Project.find(params[:project_id])
    elsif params[:user_id]
      commentable = User.find(params[:user_id])
    else
      raise 'Invalid Commentable'
    end
    @comment = commentable.comments.build(comment_params)
    @comment.user = current_user
    @comment.save

    respond_to do |format|
      format.js
      format.html {redirect_to(polymorphic_path(commentable))}
    end
  end

  def comment_params
    params.permit(:text)
  end
end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController

	def create
		# putting @project so @project will be binded to the create method
		# now you can use @project in the projects/_individual_project.html.erb
		@project = Project.find(params[:project_id])
		@pledge = Pledge.new(reward: Reward.find(params[:reward_id]))

		# ensure that the pledge user is the current user
		@pledge.user = current_user
		# find the reward based on current :reward_id
		@pledge.amount = Reward.find(params[:reward_id]).amount
		#assigning the pledge to the project
		@pledge.project = @project

		@pledge.save

		respond_to do |format|
		 	format.js  #allows controller to respond in javascript
		 	format.html { redirect_to project_url(params[:project_id]) } #allows controller to respond to html and sends it back to the correct project
		end

		if @project.pledges.sum(:amount) >= @project.funding_goal 
	 		# binding.pry
	 		@project.pledges.map{|x| x.user }.each do |backer|
	 			UserMailer.goal_met_email(backer, @project).deliver
	 			puts "MAIL SENT"
	 		end
	 	end
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :require_login, except: :index

	# calls the user_ownership method for the :edit and :update commands to check to see if the user actually owns the project before they can see the edit page.
	before_action :user_ownership, only: [:edit, :update]

	def index
		@projects = Project.order('projects.created_at DESC').page(params[:page])

		respond_to do |format|
			format.js
			format.html
		end
	end

	def show
		@project = Project.find(params[:id])
		@rewards = @project.rewards
		@comment = Comment.new

	end

	def edit
		@project = Project.find(params[:id])
	end

	def update
		@project = Project.find(params[:id])

		if @project.update_attributes(project_params)
			redirect_to project_path(@project), notice: 'Successfully Selected Reward'
		else
			render :edit
		end
	end

	def new
		# you must be required to logged in to create a new projects.  You will be directed into the login page.
		require_login
		@project = Project.new
		@project.rewards.build
	end

	def create
		@project = Project.new(project_params)
		@project.owner = current_user # When you create new project, you will insert in the current_user ID as the @project.owner

		if @project.save
			redirect_to projects_path
		else
			render :new
		end
	end

	private
	def project_params
		params.require(:project).permit(:name, :description, :start_date, :end_date, :funding_goal, :category_id, :tag_list, rewards_attributes: [:title, :description, :amount, :id, :_destroy])
	end

	# this private method checks to see if the current user owns a project
	def user_ownership
		@project = Project.find(params[:id])
		redirect_to project_path(@project) unless current_user == @project.owner
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = login(params[:email], params[:password], params[:remember_me])
    if user
      redirect_back_or_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Email or password was invalid"
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    if params[:id] =~ /\d+/
      @projects = Project.tagged_with(ActsAsTaggableOn::Tag.find(params[:id]))
    else
      @projects = Project.tagged_with(params[:id])
    end
  end

  def index
    @tags = Project.tag_counts.order(taggings_count: :desc).page(params[:page])
    respond_to :js, :html
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # automatically log in the user to the website after he's created himself - this is method gained from sorcery
      auto_login(@user)
      # used when a user tries to access a page while logged out, is asked to login
      redirect_back_or_to root_url, :notice => "Signed up!"
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @comment = Comment.new
  end

  private
  def user_params
    params.require(:user).permit(:email, :first_name, :last_name,:password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pledges_helper.rb
module PledgesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "vendor/modernizr" %>

  <%= csrf_meta_tags %>
</head>

<body>

<div class="fixed">
<nav class="top-bar" data-topbar>
  <ul class="title-area">

    <li class="name">
      <h1>
        <a href="/">
          Crowdfunder
        </a>
      </h1>
    </li>
  </ul>

  <section class="top-bar-section">

    <ul class="left">
      <li><%= link_to "All Projects", projects_path %></li>
      <li><%= link_to "Categories", categories_path %></li>
      <li><%= link_to "Tags", tags_path %></li>
    </ul>

    <ul class="right">
      <% if current_user %>
          <li class="has-dropdown">
            <a href="#" class="accessibility foundicon-blind"><%= current_user.name %></a>
            <ul class="dropdown">
              <li><%= link_to 'My Profile', user_path(current_user) %></li>
              <li><a href="#">My Projects</a></li>
              <li><a href="#">My Pledges</a></li>
              <li><%= link_to "Create Project", new_project_path %></li>
              <li><%= link_to "Log Out", :logout %></li>
            </ul>
          </li>
      <% else %>
          <li><%= link_to "Sign up", new_user_path %></li>
          <li><%= link_to "log in", :login %></li>
      <% end %>
    </ul>

  </section>
</nav>
</div>

<%= yield %>

<footer class="row">
  <div class="large-12 columns">
    <hr>
    <div class="row">
      <div class="large-6 columns">
        <p>© Copyright no one at all. Go to town.</p>
      </div>
      <div class="large-6 columns">
        <ul class="inline-list right">
          <li><a href="#">Link 1</a></li>
          <li><a href="#">Link 2</a></li>
          <li><a href="#">Link 3</a></li>
          <li><a href="#">Link 4</a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>




















<%= javascript_include_tag "application" %>
</body>
</html>

app/views/shared/_comments_form.html.erb
<%= form_tag polymorphic_path([commentable, Comment]), remote: true do %>
    <div id="comment_form_errors">
      <% if @comment.errors %>
          <%= render partial: 'comments/comment_errors' %>
      <% end %>
    </div>
    <%= text_field_tag :text, nil, placeholder: 'Write your comment here' %>
    <%= submit_tag 'Submit', class: 'button' %>
<% end %>

app/views/shared/_comments_section.html.erb
<div id="comments" class="large-12 columns">
  <h3>Comments</h3>
  <% comments.each do |comment| %>
    <%= render comment %>
  <% end %>

</div>
<%= render partial: 'shared/comments_form', locals: {commentable: commentable } %>